name: Publish Imager
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:


    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      PROJECT_PATH:   ImagerAvalonia.Desktop
      GUI_PATH: gui
      CORE_PATH: core
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ImagerMicroscopy/Imager.GUI
        ssh-key: ${{ secrets.GUI_CLONE }}
        path: ${{ env.GUI_PATH }}


     # Publish Binaries
    - name: Publish GUI
      run:  |
        $guiPath = Join-Path $env:GUI_PATH $env:PROJECT_PATH
        dotnet publish $guipath -r win-x64 -c Release --self-contained true -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:IsTestProject=false -p:EnableCodeCoverage=false -o Release
  
    - name: Clone Core
      uses: actions/checkout@v4
      with:
        repository: ImagerMicroscopy/Imager.Core
        ssh-key: ${{ secrets.CORE_CLONE }}
        path: ${{ env.CORE_PATH }}

    - name: Build Core
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '8.8.4' # Exact version of ghc to use
        enable-stack: true
        stack-version: 'latest'
        cache: true
    - run: |
           cd $env:CORE_PATH
           stack build . 
           $installRoot = stack path --local-install-root
           New-Item -ItemType Directory -Force -Path build
           New-Item -ItemType Directory -Force -Path build\Plugins
           New-Item -ItemType Directory -Force -Path build\PluginConfigurations
           Copy-Item "$installRoot\bin\*" build -Recurse
           Copy-Item "build\*" -Destination "..\Release" -Recurse -Force
           Compress-Archive -Path  "..\Release" -DestinationPath  "..\Release\Imager-Release-winx64.zip"

  
    # Upload Binaries
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Imager-Release-winx64
        path: Release\Imager-Release-winx64.zip
